<template>
    <div>
        <Gnb />

        <div class="main-container">
            <div class="side-container">
                <p class="side-title">ICONS</p>
                <div class="side-divider"></div>
                <ul class="side-nav">
                </ul>
            </div>
        </div>
    </div>
    
</template>

<script>
import Gnb from '@/view/components/Gnb'
import '@/assets/common.css'
export default {
    components :{
        Gnb
    }
}
</script>

<style scoped>
</style>

